# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print("NumPy version:", np.__version__)
print("NumPy configuration:", np.show_config())

NumPy version: 1.20.3
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
NumPy configuration: None


**3. Create a 1D array of zeros of size 10 of type float32**

In [4]:
np.zeros(10, dtype=np.float32)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

**4. Print the memory size of the array below**

In [5]:
Z = np.zeros((32,12))
# Include your solution below
print("Memory size of array Z in bytes: ", Z.size * Z.itemsize)

Memory size of array Z in bytes:  3072


**5. Create a 1D array with values ranging from 10 to 58**

In [6]:
np.arange(10,59)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

**6. Reverse the order of the values in the vector (first element becomes last)**

In [7]:
a = np.arange(10)
# Include your solution below
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**8. Create a 3x3 identity matrix**

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. Find and print the maximum values of each column in the array below** 

In [10]:
Z = np.random.random((10,11))
# Include your solution below

print("Max values from each column = \n", np.amax(Z, axis=0))

Max values from each column = 
 [0.86543944 0.86110935 0.98769433 0.84633575 0.977565   0.9358677
 0.84325183 0.99455507 0.98929157 0.7775307  0.93885299]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [11]:
m = np.ones((7,7))
m[1:-1,1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [12]:
Z = np.ones((5,5))
# Include your solution below

np.pad(Z, ((1,1), (1,1)), constant_values=(0))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [13]:
Z = np.random.uniform(0,10,10)
# Include your solution below

print("Z= \n", Z)

P = Z.astype(int)
print("\nPositive Integers = \n", P[P>0])

Z= 
 [5.59038753 9.05703037 4.49114798 9.71341452 1.23763424 4.75344992
 1.58898635 8.62652577 1.91047877 0.47732226]

Positive Integers = 
 [5 9 4 9 1 4 1 8 1]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [14]:
np.tile(np.arange(0,5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [15]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

**15. Create a random vector of size 10 and sort it**

In [16]:
np.sort(np.random.rand(10))

array([0.07406254, 0.16179661, 0.16401615, 0.21230638, 0.31402502,
       0.55659092, 0.66246397, 0.7130492 , 0.72075881, 0.86196823])

**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [17]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below

R,T = np.sqrt(X**2+Y**2), np.arctan2(Y,X)
print("R= \n", R)
print("\nT= \n", T)

R= 
 [1.29090346 0.8580653  0.20624287 0.79626449 0.18400933 0.84258021
 0.52177208 0.15332421 0.41714005 0.84331547]

T= 
 [0.83074182 0.19928736 1.32672536 0.50679909 0.11850969 0.56761374
 1.4144585  0.1955029  1.30578696 0.4583783 ]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [18]:
a = np.random.random(10)
print("original vector= \n", a)

a[a.max() == a] = 0
print("\nreplace max value by 0 = \n", a)

original vector= 
 [0.44419449 0.44431108 0.35964414 0.79376473 0.44591019 0.07620883
 0.01885374 0.88803625 0.2707283  0.91424312]

replace max value by 0 = 
 [0.44419449 0.44431108 0.35964414 0.79376473 0.44591019 0.07620883
 0.01885374 0.88803625 0.2707283  0.        ]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [19]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
print("Z= \n", Z)
print("\nNearest value of z =", '%s' %(z)," is ", Z.flat[np.abs(Z-z).argmin()])

Z= 
 [0.08637985 0.44818303 0.8745433  0.19608929 0.32057693 0.42750204
 0.13669677 0.64299007 0.12032993 0.09546952]

Nearest value of z = 0.5  is  0.4481830306137621


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [20]:
Z = np.arange(1,6)[::-1]
# Include your solution below

z = np.zeros(3)
np.insert(np.broadcast_to(z, (Z.size, z.size)), 0, Z, axis=1).ravel()[:-3]

array([5., 0., 0., 0., 4., 0., 0., 0., 3., 0., 0., 0., 2., 0., 0., 0., 1.])

**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [21]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below

print("Method #1 np.dot(B,A) = \n")
print(np.dot(B,A), "\n\n")

# or this method
print("Method #2 = \n")
print("np.dot(A[:,:,0]= \n", np.dot(A[:,:,0],B))
print("np.dot(A[:,:,1]= \n", np.dot(A[:,:,1],B))
print("np.dot(A[:,:,2]= \n", np.dot(A[:,:,2],B))

Method #1 np.dot(B,A) = 

[[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]] 


Method #2 = 

np.dot(A[:,:,0]= 
 [[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]
np.dot(A[:,:,1]= 
 [[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]
np.dot(A[:,:,2]= 
 [[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]


**21. Swap the first and second rows of the 2D array below**

In [22]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]



**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    