# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print("NumPy version:", np.__version__)
print("NumPy configuration:", np.show_config())

NumPy version: 1.20.3
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
NumPy configuration: None


**3. Create a 1D array of zeros of size 10 of type float32**

In [4]:
arr = np.zeros(10,dtype=np.float32) #set an array filled with zeros with data type float32
print(arr)
print(type(arr[0]))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.float32'>


**4. Print the memory size of the array below**

In [5]:
Z = np.zeros((32,12))
# Include your solution below

#Python way
#getsizeof returns size of an array in bytes
from sys import getsizeof
print(getsizeof(Z), "bytes")

#Numpy way
print("Memory size of array Z in bytes: ", Z.size * Z.itemsize)

3192 bytes
Memory size of array Z in bytes:  3072


**5. Create a 1D array with values ranging from 10 to 58**

In [6]:
#to include 58, we arrange from 10 to 59
arr = np.arange(10,59)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [7]:
a = np.arange(10)
# Include your solution below

print("Original array:")
print(a)
print("Reverse array:") 
a = a[::-1] #reversing the order of the values in the vector
print(a)

Original array:
[0 1 2 3 4 5 6 7 8 9]
Reverse array:
[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [8]:
A =  np.arange(0, 9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [9]:
A=np.identity(3)
print('3x3 identity matrix:')
print(A)

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [10]:
Z = np.random.random((10,11))
# Include your solution below

M = np.amax(Z, axis=0) #retrieves the maximum values of each column in array Z
print("Max values of each column = \n", M) 

Max values of each column = 
 [0.93209589 0.94672182 0.99140333 0.93653811 0.95846024 0.94737351
 0.84981164 0.82961834 0.9927342  0.77079639 0.89311202]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [11]:
a = np.ones((7,7)) # creating a 7X7 array with with all the values as 1
a[1:-1,1:-1]=0 # slicing the array so that only the borders are 1's and the value everywhere else is 0
print('Array with 1s on the border: \n', a) #printing the desired 7X7 array

Array with 1s on the border: 
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [12]:
Z = np.ones((5,5))
# Include your solution below

Z = np.pad(Z,1) # using the pad() function to pad Z with zeros
print('Array padded with 0s: \n', Z) # printing the array Z

Array padded with 0s: 
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [13]:
Z = np.random.uniform(0,10,10)
# Include your solution below

# Solution 1
Y= np.trunc(Z) #Return the truncated value of the input array elements
# Solution 2
# Y= Z.astype(int)
print("The random array of positive numbers: ")
print(Z)
print("The integer part of the random array of positive numbers: ")
print(Y)

The random array of positive numbers: 
[6.82728898 7.49146439 0.23937258 4.92366113 4.61724973 3.85230998
 5.85193197 4.20278352 6.01606331 6.78732374]
The integer part of the random array of positive numbers: 
[6. 7. 0. 4. 4. 3. 5. 4. 6. 6.]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [14]:
arr= np.arange(5) #1D array with values ranging from 0 to 4
repetitions = (5, 1) # The number of repetitions of arr along each axis
Z= np.tile(arr, repetitions) #Repeating arr
print("The 5x5 matrix with rows with equal values ranging from 0 to 4:")
print(Z)

The 5x5 matrix with rows with equal values ranging from 0 to 4:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [15]:
# Solution 1: Create the vector of size 10+2 with values ranging from 0 to 1 (0 and 1 included) and then exclude the start (0) and the end (1) using [1:-1]
x = np.linspace(0,1,12)[1:-1]
#Solution 2: Create the vector of size 10+1 with values ranging from 0 to 1 (0 included and 0 excluded) and then exclude the start (0) using [1:]
# x = np.linspace(0,1,11,endpoint=False)[1:]
# Use linspace to create a vector of size 10+2 including the start and
# numpy.linspace(start, stop, num=10, endpoint=False, retstep=False, dtype=None, axis=0)
print("Vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)")
print(x)

Vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [16]:
v = np.random.rand(10) #create random vector of size 10
sv = np.sort(v) #sort vector and assign to a variable

print("Random vector of size 10 = \n", v)
print()
print("Sorted vector = \n", sv)

Random vector of size 10 = 
 [0.39414197 0.87092387 0.30883641 0.44452771 0.92137192 0.93648679
 0.21962149 0.87356973 0.9746149  0.1203578 ]

Sorted vector = 
 [0.1203578  0.21962149 0.30883641 0.39414197 0.44452771 0.87092387
 0.87356973 0.92137192 0.93648679 0.9746149 ]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [17]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below

R,T = np.sqrt(X**2+Y**2), np.arctan2(Y,X) #formula to convert and get the radius and theta of cartesian coordinates
print("R = \n", R)
print()
print("T = \n", T)

R = 
 [0.48552848 0.59439368 0.40347482 1.00602153 0.80707514 0.18410133
 0.86465708 0.81335808 0.69207401 0.36436574]

T = 
 [1.19142629 0.55661067 0.41010413 1.09195106 0.66389452 0.95817954
 0.53900538 0.04571365 0.80682625 1.4870834 ]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [18]:
a = np.random.random(10) #create random vector of size 10
print("Random vector of size 10 = \n", a)

a[a.max() == a] = 0 #replace maximum value by 0
print()
print("Max value replaced by 0 = \n", a)

Random vector of size 10 = 
 [0.08844527 0.05675388 0.94647832 0.64689765 0.02356214 0.22148441
 0.56604492 0.28525062 0.677881   0.14548654]

Max value replaced by 0 = 
 [0.08844527 0.05675388 0.         0.64689765 0.02356214 0.22148441
 0.56604492 0.28525062 0.677881   0.14548654]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [19]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below

'''The operation finds the minimum value after performing absolute difference between elements of Z and z 
by iterating over the elements using the flat function. 
'''
nearest_value = Z.flat[np.abs(Z - z).argmin()]
print(f' The nearest value to z is: {nearest_value}')

 The nearest value to z is: 0.5776273104619915


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [20]:
Z = np.arange(5)[::-1]
# Include your solution below

zeros = 3

# Craete an array fill with zeros with number of zeros equal to the interleaved zeros and the original values
new_array = np.zeros(len(Z) + (len(Z)-1)*(zeros))
new_array[::zeros+1] = Z #Broadcasting
print(Z)
print(f'Vector with zeros interleaved between each value: {new_array}')

[4 3 2 1 0]
Vector with zeros interleaved between each value: [4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [21]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below

# multiplied_array = (A*B[:,:, None]) # Element-wise multiplication
multiplied_array = np.dot(B,A) # Element-wise multiplication carried out by making column of B equal to row of A.
print('Element-wise multiplication')
print(multiplied_array)

Element-wise multiplication
[[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]]


**21. Swap the first and second rows of the 2D array below**

In [22]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below

W[[0,1]] = W[[1,0]]  # First row and and second row swapped
print('Swapped Array: ')
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Swapped Array: 
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [24]:
def bbox(img):
    #include your solution below
    mbb = np.nonzero(img) #retrieve an array of nonzero values from image
    r1,c1 = mbb[0].min(), mbb[1].min() #get the lowest value of all rows and columns
    r2,c2 = mbb[0].max(), mbb[1].max() #get the highest value of all rows and columns
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [25]:
# Solution 1
def moving_average(x,N = 3):
    new_size = N * np.ceil(x.size / N) #calculates new array size to make 'x' divisible by 'N'
    add_zero = new_size.astype(int) - x.size #get the number of zeros to be added to original array 'x'
    x = np.pad(x, (0, add_zero), constant_values=(0)) #pad zeros into original array
    shape = (int(x.size/N) , N) # (row, column)
    strides = (N*x.strides[0], x.strides[0]) # Number of bytes to jump-over in the memory
    roll_array = np.lib.stride_tricks.as_strided(x, shape=shape, strides=strides) #Create the view
    avg_array= roll_array.mean(axis=1) #Compute the arithmetic mean along columns
    return avg_array

# Solution 2
# def moving_average(x,N = 3):
#     new_size = N * np.ceil(x.size / N) #calculates new array size to make 'x' divisible by 'N'
#     add_zero = new_size.astype(int) - x.size #get the number of zeros to be added to original array 'x'
#     new_x = np.pad(x, (0, add_zero), constant_values=(0)) #pad zeros into original array
#     ca = np.cumsum(new_x)[N-1::N] #calculates the cumulative sum of each value in array and filters by multiples of 'N'
#     ca[1:] = np.diff(ca) #calculates the difference between every value after the first index
#     return ca / N #calculates the moving average

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [26]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include your solution here

A = np.repeat(np.arange(len(C)), C) # using the repeat function to have the data repeated for length(C) times
print('A:', A) # printing array A
print('np.bincount(A): {} == C'.format(np.bincount(A))) # np.bincount(A) == C

[0 2 1 1 2 0 1]
A: [1 1 2 3 4 4 6]
np.bincount(A): [0 2 1 1 2 0 1] == C


**25. Find the most frequent value in the array below?**

In [27]:
Z = np.random.randint(0,10,50)
# Include your solution below

print("Original array:")
print(Z)
print("The most frequent value in the array:")
print(np.bincount(Z).argmax()) #defining the most frequent value in the array

Original array:
[1 3 9 6 3 0 9 2 1 7 4 7 6 9 8 3 9 8 2 0 6 7 0 0 4 2 4 5 1 9 9 8 0 2 5 1 1
 3 2 1 8 6 6 1 0 6 1 0 7 6]
The most frequent value in the array:
1


**26. Write a function to return the n largest values of an array** 

In [28]:
def nlargest(a,n = 5):
    # Include your solution here
    Z.sort() # sort the array Z
    return Z[-n:] #return last n elements

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

[9995 9996 9997 9998 9999]
