# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [2]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [3]:
import numpy as np

**2. Print the numpy version and the configuration**

**3. Create a 1D array of zeros of size 10 of type float32**

**4. Print the memory size of the array below**

In [4]:
import numpy as np

Z = np.zeros((32,12))
# Include your solution below

**5. Create a 1D array with values ranging from 10 to 58**

**6. Reverse the order of the values in the vector (first element becomes last)**

In [5]:
a = np.arange(10)
# Include your solution below

**7. Create a 3x3 matrix with values ranging from 0 to 8**

**8. Create a 3x3 identity matrix**

**9. Find and print the maximum values of each column in the array below** 

In [6]:
Z = np.random.random((10,11))
# Include your solution below

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [7]:
Z = np.ones((5,5))
# Include your solution below

**12. Extract the integer part of the random array of positive numbers below**

In [8]:
Z = np.random.uniform(0,10,10)
# Include your solution below
# Solution 1
Y= np.trunc(Z) #Return the truncated value of the input array elements
# Solution 2
# Y= Z.astype(int)
print("The random array of positive numbers: ")
print(Z)
print("The integer part of the random array of positive numbers: ")
print(Y)

The random array of positive numbers: 
[4.60844814 7.3573283  3.16374251 6.51915423 5.90454699 4.2250691
 6.39705666 2.95784252 2.32406866 0.92620513]
The integer part of the random array of positive numbers: 
[4. 7. 3. 6. 5. 4. 6. 2. 2. 0.]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [9]:
arr= np.arange(5) #1D array with values ranging from 0 to 4
repetitions = (5, 1) # The number of repetitions of arr along each axis
Z= np.tile(arr, repetitions) #Repeating arr
print("The 5x5 matrix with rows with equal values ranging from 0 to 4:")
print(Z)


The 5x5 matrix with rows with equal values ranging from 0 to 4:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [10]:
# Solution 1: Create the vector of size 10+2 with values ranging from 0 to 1 (0 and 1 included) and then exclude the start (0) and the end (1) using [1:-1]
x = np.linspace(0,1,12)[1:-1]
#Solution 2: Create the vector of size 10+1 with values ranging from 0 to 1 (0 included and 0 excluded) and then exclude the start (0) using [1:]
# x = np.linspace(0,1,11,endpoint=False)[1:]
# Use linspace to create a vector of size 10+2 including the start and
# numpy.linspace(start, stop, num=10, endpoint=False, retstep=False, dtype=None, axis=0)
print("Vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)")
print(x)


Vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [11]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below


**17. Create random vector of size 10 and replace the maximum value by 0**

**18. Find the nearest value from a given value (z) in an array (Z)**

In [50]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below

'''The operation finds the minimum value after performing absolute difference between elements of Z and z 
by iterating over the elements using the flat function. 
'''
nearest_value = Z.flat[np.abs(Z - z).argmin()]
print(f' The nearest value to z is: {nearest_value}')

 The nearest value to z is: 0.5876667193567955


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [42]:
Z = np.arange(5)[::-1]

# Include your solution below
zeros = 3

# Craete an array fill with zeros with number of zeros equal to the interleaved zeros and the original values
new_array = np.zeros(len(Z) + (len(Z)-1)*(zeros))
new_array[::zeros+1] = Z #Broadcasting
print(Z)
print(f'Vector with zeros interleaved between each value: {new_array}')

np.ndim(new_array)

[4 3 2 1 0]
Vector with zeros interleaved between each value: [4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


1

**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [20]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
multiplied_array = (A*B[:,:, None]) # Element-wise multiplication 
print('Element-wise multiplication')
print(multiplied_array)


Element-wise multiplication
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [37]:
W = np.arange(30).reshape(6,5)
print('Original Array')
print(W)
print()
# Include your solution below
W[[0,1]] = W[[1,0]]  # First row and and second row swapped
print('Swapped Array: ')
print(W)



Original Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Swapped Array: 
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [16]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

NameError: name 'r1' is not defined

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
# Solution 1
def moving_average(x,N = 3):
    shape = (int(x.size/N) , N) # (row, column)
    strides = (N*x.strides[0], x.strides[0]) # Number of bytes to jump-over in the memory
    roll_array = np.lib.stride_tricks.as_strided(x, shape=shape, strides=strides) #Create the view
    avg_array= roll_array.mean(axis=1) #Compute the arithmetic mean along columns
    return avg_array

# Solution 2
# def moving_average(x,N = 3):
#     ca = np.cumsum(x)[N-1::N] # Cumulative sum of the elements
#     ca[1:] = np.diff(ca)  #Calculate the difference between the elements
#     return ca / N #return the average

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    